from typing import Dict, List
from langchain.schema import HumanMessage, AIMessage
from datetime import datetime
from fpdf import FPDF
import pandas as pd
import re
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import io

def format_campaign_kit(messages: List[Dict]) -> str:
    """
    Formats agent responses into a structured markdown document.
    
    Args:
        messages (List[Dict]): List of message dictionaries containing:
            - For brainstorm mode: agent, response, input
            - For calendar mode: agent, response
            
    Returns:
        str: Formatted markdown document
    """
    if not messages:
        return ""
        
    # Check if this is a calendar result (no input field)
    is_calendar = "input" not in messages[0]
    
    # Start with title and timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    markdown = f"# Ghostwriter {'Calendar' if is_calendar else 'Campaign Kit'} – {timestamp}\n\n"
    
    # Add intro paragraph
    markdown += "_This document was generated by your AI creative team. Each section reflects input from a specialized agent._\n\n"
    
    # Add prompt section for brainstorm mode
    if not is_calendar:
        user_prompt = messages[0]["input"]
        markdown += "**Original Prompt**\n\n"
        markdown += f"> {user_prompt}\n\n"
        markdown += "---\n\n"
    
    # Group messages by agent
    agent_responses = {}
    for msg in messages:
        agent = msg["agent"]
        if agent not in agent_responses:
            agent_responses[agent] = []
        agent_responses[agent].append(msg["response"])
    
    # Add each agent's responses as a section
    for agent_name, responses in agent_responses.items():
        # Format the agent name for the heading
        formatted_name = agent_name.title()
        
        # Add the section
        markdown += f"## {formatted_name}'s Contribution\n\n"
        # Join all responses from this agent
        markdown += "\n\n".join(responses) + "\n\n"
        markdown += "---\n\n"
    
    return markdown

def save_campaign_kit(markdown_content: str, filename: str = "campaign_kit.md") -> None:
    """
    Saves the formatted campaign kit to a markdown file.
    
    Args:
        markdown_content (str): The formatted markdown content
        filename (str): The name of the file to save to
    """
    with open(filename, "w", encoding="utf-8") as f:
        f.write(markdown_content)

def export_to_pdf(markdown_text: str, filename: str = "kit.pdf") -> bytes:
    """
    Export markdown content to PDF using reportlab.
    
    Args:
        markdown_text (str): The markdown content to export
        filename (str): The output filename
        
    Returns:
        bytes: The PDF file as bytes
    """
    # Create a buffer to store the PDF
    buffer = io.BytesIO()
    
    # Create the PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )
    
    # Register fonts
    try:
        pdfmetrics.registerFont(TTFont('NotoSans', 'fonts/NotoSans-Regular.ttf'))
        pdfmetrics.registerFont(TTFont('NotoSans-Bold', 'fonts/NotoSans-Bold.ttf'))
    except:
        # Fallback to built-in fonts if custom fonts fail
        pass
    
    # Create styles
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name='Custom',
        fontName='NotoSans',
        fontSize=11,
        leading=14,
        spaceAfter=10
    ))
    styles.add(ParagraphStyle(
        name='CustomBold',
        fontName='NotoSans-Bold',
        fontSize=11,
        leading=14,
        spaceAfter=10
    ))
    
    # Story to hold all elements
    story = []
    
    # Function to clean text
    def clean_text(text):
        replacements = {
            '–': '-',  # en dash
            '—': '-',  # em dash
            '"': '"',  # smart quotes
            '"': '"',
            ''': "'",
            ''': "'",
            '…': '...',
            '•': '*',
            '\t': '    '  # Replace tabs with spaces
        }
        for old, new in replacements.items():
            text = text.replace(old, new)
        return text
    
    # Process markdown lines
    lines = markdown_text.split('\n')
    current_table_data = []
    
    for line in lines:
        line = clean_text(line)
        
        # Handle headers
        if line.startswith('#'):
            level = len(re.match(r'^#+', line).group())
            text = line.lstrip('#').strip()
            font_size = max(16 - level, 11)
            style = ParagraphStyle(
                name=f'Header{level}',
                parent=styles['CustomBold'],
                fontSize=font_size,
                spaceAfter=20
            )
            story.append(Paragraph(text, style))
            story.append(Spacer(1, 12))
        
        # Handle table rows
        elif line.startswith('|'):
            parts = [part.strip() for part in line.split('|')[1:-1]]
            if line.startswith('|---'):  # Table header separator
                if current_table_data:
                    # Create and style the table
                    table = Table(current_table_data)
                    table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTNAME', (0, 0), (-1, 0), 'NotoSans-Bold'),
                        ('FONTSIZE', (0, 0), (-1, 0), 11),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
                        ('FONTNAME', (0, 1), (-1, -1), 'NotoSans'),
                        ('FONTSIZE', (0, 1), (-1, -1), 10),
                        ('GRID', (0, 0), (-1, -1), 1, colors.black),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ]))
                    story.append(table)
                    story.append(Spacer(1, 12))
                    current_table_data = []
            else:
                current_table_data.append(parts)
        
        # Handle regular text
        else:
            if line.strip():
                story.append(Paragraph(line, styles['Custom']))
                story.append(Spacer(1, 5))
    
    # Build the PDF
    try:
        doc.build(story)
        return buffer.getvalue()
    except Exception as e:
        print(f"Error generating PDF: {str(e)}")
        # Return a simple error PDF
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        c.setFont("Helvetica", 12)
        c.drawString(72, 750, "Error generating PDF. Please check the content for incompatible characters.")
        c.save()
        return buffer.getvalue()

def export_to_csv(calendar_data: List[Dict], filename: str = "calendar.csv") -> bytes:
    """
    Export calendar data to CSV.
    
    Args:
        calendar_data (List[Dict]): List of calendar entries
        filename (str): The output filename
        
    Returns:
        bytes: The CSV file as bytes
    """
    df = pd.DataFrame(calendar_data)
    return df.to_csv(index=False).encode('utf-8')

def export_by_agent(messages: List[Dict], agent: str) -> str:
    """
    Export messages from a specific agent.
    
    Args:
        messages (List[Dict]): List of all messages
        agent (str): Agent name to filter by
        
    Returns:
        str: Formatted markdown content
    """
    filtered = [m for m in messages if m["agent"] == agent]
    return format_campaign_kit(filtered)

def export_by_week(messages: List[Dict], week_index: int) -> str:
    """
    Export messages from a specific week.
    
    Args:
        messages (List[Dict]): List of all messages
        week_index (int): Week index (0-based)
        
    Returns:
        str: Formatted markdown content
    """
    # Find messages with week tag
    week_messages = []
    for msg in messages:
        if "week" in msg and msg["week"] == week_index:
            week_messages.append(msg)
    return format_campaign_kit(week_messages)

def export_by_section(calendar_text: str, section_name: str) -> str:
    """
    Export a specific section from the calendar text.
    
    Args:
        calendar_text (str): The full calendar text
        section_name (str): Name of the section to extract
        
    Returns:
        str: Formatted markdown content for the section
    """
    try:
        # Find the section
        section_marker = f"## {section_name}"
        if section_marker not in calendar_text:
            return ""
        
        # Extract the section content
        section_content = calendar_text.split(section_marker)[1].split("##")[0].strip()
        
        # Format the output
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        return f"""# {section_name} – {timestamp}

{section_content}
"""
    except Exception as e:
        return f"Error extracting section: {str(e)}"

def export_calendar_with_scores(calendar: List[Dict], scores: List[Dict]) -> pd.DataFrame:
    """
    Merge calendar entries with Eva's scores into a single DataFrame.
    
    Args:
        calendar (List[Dict]): List of calendar entries
        scores (List[Dict]): List of Eva's scores for entries
        
    Returns:
        pd.DataFrame: Combined DataFrame with scores
    """
    # Create base calendar DataFrame
    calendar_df = pd.DataFrame(calendar)
    
    # Create scores DataFrame
    scores_df = pd.DataFrame(scores)
    
    # Merge on appropriate key (assuming post text/copy is the key)
    if 'Copy' in calendar_df.columns and 'post' in scores_df.columns:
        merged_df = pd.merge(
            calendar_df,
            scores_df,
            left_on='Copy',
            right_on='post',
            how='left'
        )
    else:
        merged_df = calendar_df
    
    return merged_df

def export_per_platform_csv(calendar_entries: List[Dict]) -> Dict[str, str]:
    """
    Group calendar entries by platform and export each as CSV.
    
    Args:
        calendar_entries (List[Dict]): List of calendar entries
        
    Returns:
        Dict[str, str]: Dictionary mapping platform names to CSV content
    """
    # Convert to DataFrame
    df = pd.DataFrame(calendar_entries)
    
    # Group by platform
    platform_groups = df.groupby('Platform')
    
    # Create CSV for each platform
    platform_csvs = {}
    for platform, group in platform_groups:
        csv_content = group.to_csv(index=False).encode('utf-8')
        platform_csvs[platform] = csv_content
    
    return platform_csvs

def create_calendar_matrix(calendar_entries: List[Dict]) -> pd.DataFrame:
    """
    Create a matrix view of the calendar with dates as rows and platforms as columns.
    
    Args:
        calendar_entries (List[Dict]): List of calendar entries
        
    Returns:
        pd.DataFrame: Matrix-style DataFrame
    """
    # Convert to DataFrame
    df = pd.DataFrame(calendar_entries)
    
    # Convert Date to datetime if it's not already
    df['Date'] = pd.to_datetime(df['Date'])
    
    # Create pivot table
    matrix = pd.pivot_table(
        df,
        values='Copy',
        index='Date',
        columns='Platform',
        aggfunc=lambda x: '\n'.join(x),
        fill_value=''
    )
    
    # Sort by date
    matrix = matrix.sort_index()
    
    return matrix 